import type { Metadata } from "next";
import "../styles/globals.scss";
import { CoreProvider } from "@/components/provider/CoreProvider/CoreProvider";

export const metadata: Metadata = {
  icons: "/images/general/logo.svg",
  title: "آکادمی روانشناسی دکتریت",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <CoreProvider>{children}</CoreProvider>
      </body>
    </html>
  );
}
