import type { Metadata } from "next";
import "../styles/globals.scss";

export const metadata: Metadata = {
  icons: "/images/general/logo.svg",
  title: "آکادمی روانشناسی دکتر تریت",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>{children}</body>
    </html>
  );
}
